"""knowledge embeddings cache

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 15:52:07.613672
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_embeddings',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('content_hash', 'model')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_embeddings')
    # ### end Alembic commands ###
